### ISSUE TITLE
[Question] How do i use this in atomic-css design?

### ISSUE THREAD

**Issue by Nemure231** [feat-agency/vite-plugin-webfont-dl#31]
hi, is there any way to use it in atomic css design like tailwindcss/windicss/unocss? 

Or i must do it manually like official example:

```CSS
h1 {
  font-family: 'Press Start 2P', cursive;
}

h2 {
  font-family: 'Fira Code', monospace;
}
```
Many thanks!

**Comment by mateenagy** [comment]
Hi @Nemure231 👋 

I look into the question and you have two option:
1. Set it manually as you mentioned:
```css
h1 {
    font-family: 'Roboto', sans-serif;
}
```

2. You can use the config files tailwind/windicss/unocss provide to you (this code snippet will be the same with all three)
```js
theme: {
    extend: {
      fontFamily: {
         sans: ['Roboto'],
      },
   },
},
```
and use it like this:
```html
<p class="font-sans">Hello World</p>
```

Tailwind also accept this syntax (without touching the config file):
```html
<p class="font-['Roboto']">Hello World</p>
```

I only tried with Tailwind + Vite + Vue (but windicss and unocss works the same I think) and every way works like charm.

Here are the related documentations of how you can do it:

Tailwind:
https://tailwindcss.com/docs/font-family
Windicss:
https://windicss.org/utilities/general/typography.html#font-family
unocss:
https://unocss.dev/guide/config-file

I close this issue because it's not a package related issue.
