### ISSUE TITLE
Question: Bad web vitals with the vite plugin?

### ISSUE THREAD

**Issue by Zankel-Engineering** [feat-agency/vite-plugin-webfont-dl#35]
Hi feat-agency,

first I would like to thank you for this nice plugin. I currently build my website with Qwik and use your plugin since in Germany it is not allowed to talk to the Google CDN from a public website.

Unfortunately I recognized that the web vitals are not that good with it. Is there a reason why so many different woff files are attached to the build?

The website is just a preview but you can check it here:

https://pagespeed.web.dev/analysis/https-preview-zankel-engineering-pages-dev/i7ouid2n3u?hl=DE&form_factor=mobile
and here
https://www.debugbear.com/test/website-speed/7eemCpD4/requests 

Is there any possibility to optimize this behaviour? The LCP gets bad for that reason.

Thanks in advance.

Sebastian

**Comment by 0xb4lint** [comment]
Hi @Zankel-Engineering!

> Is there a reason why so many different woff files are attached to the build?

The plugin is downloading all the font files referenced in the CSS. As you can see in the sample CSS below, there are defined unicode ranges for different files, it's up to the client's browser if it uses / downloads the actual font files or not.

> Unfortunately I recognized that the web vitals are not that good with it.

According to our performance checks, using this plugin improves the overall web vitals. Did you checked with Google Fonts vs. using `vite-plugin-webfont-dl`?

<details>
  <summary>Sample CSS with <a href="https://fonts.googleapis.com/css2?family=Roboto&display=swap">Roboto regular weight only</a>: </summary>

```css
/* cyrillic-ext */
@font-face {
  font-family: 'Roboto';
  font-style: normal;
  font-weight: 400;
  font-display: swap;
  src: url(https://fonts.gstatic.com/s/roboto/v30/KFOmCnqEu92Fr1Mu72xKKTU1Kvnz.woff2) format('woff2');
  unicode-range: U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F;
}
/* cyrillic */
@font-face {
  font-family: 'Roboto';
  font-style: normal;
  font-weight: 400;
  font-display: swap;
  src: url(https://fonts.gstatic.com/s/roboto/v30/KFOmCnqEu92Fr1Mu5mxKKTU1Kvnz.woff2) format('woff2');
  unicode-range: U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116;
}
/* greek-ext */
@font-face {
  font-family: 'Roboto';
  font-style: normal;
  font-weight: 400;
  font-display: swap;
  src: url(https://fonts.gstatic.com/s/roboto/v30/KFOmCnqEu92Fr1Mu7mxKKTU1Kvnz.woff2) format('woff2');
  unicode-range: U+1F00-1FFF;
}
/* greek */
@font-face {
  font-family: 'Roboto';
  font-style: normal;
  font-weight: 400;
  font-display: swap;
  src: url(https://fonts.gstatic.com/s/roboto/v30/KFOmCnqEu92Fr1Mu4WxKKTU1Kvnz.woff2) format('woff2');
  unicode-range: U+0370-03FF;
}
/* vietnamese */
@font-face {
  font-family: 'Roboto';
  font-style: normal;
  font-weight: 400;
  font-display: swap;
  src: url(https://fonts.gstatic.com/s/roboto/v30/KFOmCnqEu92Fr1Mu7WxKKTU1Kvnz.woff2) format('woff2');
  unicode-range: U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+0300-0301, U+0303-0304, U+0308-0309, U+0323, U+0329, U+1EA0-1EF9, U+20AB;
}
/* latin-ext */
@font-face {
  font-family: 'Roboto';
  font-style: normal;
  font-weight: 400;
  font-display: swap;
  src: url(https://fonts.gstatic.com/s/roboto/v30/KFOmCnqEu92Fr1Mu7GxKKTU1Kvnz.woff2) format('woff2');
  unicode-range: U+0100-02AF, U+0304, U+0308, U+0329, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF;
}
/* latin */
@font-face {
  font-family: 'Roboto';
  font-style: normal;
  font-weight: 400;
  font-display: swap;
  src: url(https://fonts.gstatic.com/s/roboto/v30/KFOmCnqEu92Fr1Mu4mxKKTU1Kg.woff2) format('woff2');
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
}
```
