### ISSUE TITLE
Text property breaks things

### ISSUE THREAD

**Issue by nstringham** [feat-agency/vite-plugin-webfont-dl#6]
if you include the `text` property it doesn't work

```js
ViteWebfontDownload(["https://fonts.googleapis.com/css?family=Roboto&text=abcdefghijklmnopqrstuvwxyz"])
```

instead it just outputs this

```css
@font-face {
  font-family: 'Roboto';
  font-style: normal;
  font-weight: 400;
  src: url(https://fonts.gstatic.com/l/font?kit=KFOmCnqEu92Fr1Me4H5VYlVeTqSU8uAnERDYbDdwE0WqKZJ5WD7r0XU&skey=a0a0114a1dcab3ac&v=v30) format('woff2');
}
```
